### ISSUE TITLE
Unable to detect Editable instance

### ISSUE THREAD

**Issue by kaynz** [Leaflet/Leaflet.Editable#100]
Hi,

I'm trying to update to latest leaflet, Leaflet.Editable and Leaflet.Editable.Drag.

Actually I'm getting this error:

![error](https://cloud.githubusercontent.com/assets/12952835/18241543/0d6ef7c0-7352-11e6-8449-ca4edafe82d3.png)

I'm not sure if this is a Leaflet.Editable error or a bug in Leaflet.Editable.Drag since _distance_ is NaN.

Also I removed all occurrences of L.Rectangle since I'm using a customized leaflet version.

**Comment by yohanboniface** [comment]
Leaflet.Editable does not need Leaflet.Editable.Drag, you should either use [Leaflet/Path.Drag.js](https://github.com/Leaflet/Path.Drag.js) or [w8r/Leaflet.Path.Drag](https://github.com/w8r/Leaflet.Path.Drag) directly.

**Comment by artuska** [comment]
When you create a map with the `new L.Map` you should pass the `editable: true` in config options:

```var map = new L.Map('leaflet', {
	center: [55.837109, 37.481232],
	zoom: 16,
	editable: true,
});```
