### ISSUE TITLE
enhancement: add editable:vertex:new event

### ISSUE THREAD

**Issue by opoto** [Leaflet/Leaflet.Editable#102]
I want to execute a function each time a new vertex is added to a polyline:
1. when clicking on map while continuing backward or forward
2. when clicking a middlemarker to convert it to a vertex

Could there be a `editable:vertex:new` event in such cases?
For 1. I can capture the `editable:drawing:click` event, but at that time the vertex is not yet added to the Polyline.
For 2. I can capture the `editable:vertex:dragend` event, but I think it is weird to get same event for a new vertex and a moved one. Or use `editable:middlemarker:mousedown`, but at that time vertex is not added to polyline yet.
Thanks

**Comment by yohanboniface** [comment]
Makes sense. I'll have a look.
