### ISSUE TITLE
Rectangle drawing broken on iOS (touch events)

### ISSUE THREAD

**Issue by xoqem** [Leaflet/Leaflet.Editable#103]
I just noticed this evening that rectangle drawing isn't quite working with touch events.  A little bit of investigation shows that onDrawingMouseDown seems to be firing twice for Rectangle Editor.  If I add this at the top of the method:

if (this._mouseDown) return;
this._mouseDown = true;

And then in onDrawingMouseUp add:

this._mouseDown = false;

It works, so it seems to have something to do with that method being triggered twice.  Interestingly Circle Editor also triggers the mouse down twice, but seems to mostly work with touch.  I temporarily added the above code for both Circle (just in case) and Rectangle editor in my own project.  I'm happy to do a Pull Request with that change, but I figured you could probably come up with a proper solution that was less hacky :).

Also, you probably already know about this feature, but Chrome has a really cool Device toolbar that I had completely forgotten about, and if you select iPad (or whatever) and refresh the page, you'll get touch events instead of mouse events, which was how I was able to track down a temporary fix more easily.

Thanks!

**Comment by yohanboniface** [comment]
Which version of Leaflet.Editable and LEaflet are you using?

**Comment by xoqem** [comment]
So locally I'm using the Leaflet.Editable from a few days ago (git hash d79b98c3).  Leaflet I'm using the tag v1.0.0-rc.3

Also, I tested on my iPad and Chrome device mode using the example from the github page http://leaflet.github.io/Leaflet.Editable/example/index.html and it seems to have a similar problem as my local build (and it looks like it is using similar versions).

**Comment by yohanboniface** [comment]
Okay thanks. I'll have a look.

**Comment by yohanboniface** [comment]
Broken since https://github.com/Leaflet/Leaflet/commit/f05af08a2c1c01fb09ee4fc47ccc568463f96f09 / https://github.com/Leaflet/Leaflet/pull/4387
Basically, on touch device, we are dealing with simulated events, which are no more taken into account by L.Draggable.
Needs more investigation for a reliable hac^C solution.

**Comment by yohanboniface** [comment]
@xoqem can you test out latest master?
