### ISSUE TITLE
How to add custom markers, polylines etc.

### ISSUE THREAD

**Issue by dborowiec10** [Leaflet/Leaflet.Editable#104]
I would like to add custom Markers to my map by extending the L.Marker class of Leaflet. However I am not sure how to extend the L.Editable from an angular-leaflet-directive so I can include my own callback for my object.
Basically I would like to have a custom control that when I click on it, it would allow me to draw/place a custom marker on the map using the plugin just like I do with normal marker.

**Comment by yohanboniface** [comment]
Use `markerClass` in the `editOptions` you pass to the map (or in the options you give to L.Editbable if you create it by hand).
