### ISSUE TITLE
Dragging vertices/map/polygon not working after deleting single vertex

### ISSUE THREAD

**Issue by LutzTrazee** [Leaflet/Leaflet.Editable#109]
In my setup i have issues with dragging after deleting vertices from a polygon. I modified some of the plugin's files but even after returning to the original state i still had the same problem. The problem disapears after clicking and dragging a middle marker.
I could help myself by including 
    L.Draggable._dragging = false;
to the onClick method right after calling 
    this.editor.onVertexMarkerClick(e);

I don't know if it's still a problem with my modifications as i could not reproduce it in your examples but maybe it's still useful to know about

**Comment by yohanboniface** [comment]
@LutzTrazee thanks for the report, but without a way to reproduce I'm a bit clueless about what I can do to help.
I'm closing the issue, but feel free to reopen if you have a way to reproduce, or if you want to discuss further.
