### ISSUE TITLE
GetBounds

### ISSUE THREAD

**Issue by flightsurvey** [Leaflet/Leaflet.Editable#110]
I have an "'editable:disable'" event on an editable polygon that creates a bounding box as a rectangle afresh from the polygon getBounds().getNorthEast() etc.

If I increase the size of the polygon then the bounding box expands but it does not shrink when I reduce the size of the polygon.

I have tried the redraw() and map.invalidateSize() to no effect.

**Comment by yohanboniface** [comment]
Yeah, for performance reasons, Leaflet.Editable only "extend" the edited path bounds. This is far from ideal, but there are case where resetting totally the bounds at each mouse move can cost.
What you need to do is to reset the bounds (create a new `this._bounds`, loop over the polygon latlngs and call `this._bounds.extend(latlng`) when needed.
I'll keep this issue open to see how this can be made easier, or maybe done automatically on disable or something like this.

**Comment by flightsurvey** [comment]
Many thanks - I'll give it a go.

**Comment by flightsurvey** [comment]
I can't find any documentation at all on _bounds.extend() - could you give me a head start on deploying it?

**Comment by yohanboniface** [comment]
http://leafletjs.com/reference-1.0.0.html#latlngbounds-extend

**Comment by flightsurvey** [comment]
Thanks

**Comment by flightsurvey** [comment]
I'm sorry - I'm probably being thick but I don't understand how to implement the bounds extend on a polygon that has had its size decreased by Editable. I've tried the following as the polygon that I want to reset the boundaries of is the only layer in a featureGroup called definedArea:

  definedArea.eachLayer(function (layer) {

    var definedAreaLatLngs = layer.getLatLngs();
    
    $.each(definedAreaLatLngs[0], function(key, value) {
        
        this._bounds.extend(value);
  
    });

  });

And, funnily enough, it doesn't work. Can anyone help me?

Thanks in advance.

**Comment by yohanboniface** [comment]
> create a new this._bounds

```
layer._bounds = L.latLngBounds();
```

You need to reset the bounds and compute it again.

**Comment by flightsurvey** [comment]
Cheers - I'll have a go.

**Comment by flightsurvey** [comment]
... and thank you very much for all of your prompt and helpful replies.
