### ISSUE TITLE
Deleted polygon still referenced in featureGroup?

### ISSUE THREAD

**Issue by flightsurvey** [Leaflet/Leaflet.Editable#112]
I'm using "this.editor.deleteShapeAt(e.latlng);" to delete a polygon that belongs to a FeatureGroup but it looks like a reference to the polygon is still held in the FeatureGroup when I process a <layer>.eachLayer() loop immediately after the deletion.

**Comment by yohanboniface** [comment]
Deleting a shape does not delete the feature.

**Comment by Cyrille37** [comment]
Hi,

I'm in the same case.
If "Deleting a shape does not delete the feature", howto deleting the feature after called `this.editor.deleteShapeAt()` ?

Thanks & cheers :-)
