### ISSUE TITLE
Disable vertex during draw

### ISSUE THREAD

**Issue by XellossT** [Leaflet/Leaflet.Editable#115]
Hi,

I want to know how to disable the vertex (icon marker) during the draw of an element.

For example, I want to draw a rectangle but without the 4 four vertex.

I found an option for the middle marker : skipMiddleMarkers but nothing for the vertex.

If you have some tips on how to access to them (for example to change the className of the element or something similar) it would be great !

Regards,
Thibaut

**Comment by yohanboniface** [comment]
Hi,

Sorry for the very late answer.
The only way I see now is to have a custom editor class that overrides `initVertexMarkers`, something like:

```javascript
var VertexLessEditor = L.RectangleEditor.extend({
    initVertexMarkers: {}
});

var myrectangle = L.rectangle(xxxx, {editorClass: VertexLessEditor});
```
