### ISSUE TITLE
polyline drawing does not work on chrome on android 

### ISSUE THREAD

**Issue by opoto** [Leaflet/Leaflet.Editable#116]
Chrome 55.0.2883.91
Android 6.0.1

To reproduce:
- open http://leaflet.github.io/Leaflet.Editable/example/undo-redo.html on Chrome on Android
- click polyline tool
- tap on map: it does not create the vertex / polyline

**Comment by girakun** [comment]
Experiencing the same issue (Android 7.1.1), But it's not only Android, touch in Windows 10 with chrome 55.0.2883.87 doesn't work either. Chrome on IOS appears to work.

**Comment by girakun** [comment]
Crated pull request #118 fixing the problem, at least for me..

**Comment by girakun** [comment]
@opoto Pull request created double coordinates, and i can't really find clean way of solving the original issue. Javascript event-handling isn't really my thing... But, I made this [Commit in my branch](https://github.com/girakun/Leaflet.Editable/commit/a80e46b94ddcd6e394dbe1f15e7af56ceac9bf01). This makes touch work in more browsers than Firefox and does not create double coordinates. But it is not really worthy of a pull request..

**Comment by opoto** [comment]
Seems to be fixed with Leaflet 1.0.3.
To confirm: please update http://leaflet.github.io/Leaflet.Editable/example/undo-redo.html to use leaflet 1.0.3
Thanks

**Comment by opoto** [comment]
Confirmed: works now!
Thanks
