### ISSUE TITLE
Very slow while editing a huge line

### ISSUE THREAD

**Issue by doubotis** [Leaflet/Leaflet.Editable#119]
Hi,

I'm testing this plugin to allow the edition of trails on a website.
Unfortunately, some trails are made of approximately 6000+ points, that means a lot of segments.

When I try to enableEdit() on it, the map becomes very laggy and the rendering of all the small markers takes ages.

Any idea to optimize the whole thing?

**Comment by ddproxy** [comment]
Use a faster machine?

6k+ points is a lot for the browser to manage. I'd suggest looking into breaking the trails into 'indexed' segment chunks that modify the primary line. But, that's an index engineering problem.

**Comment by yohanboniface** [comment]
#15 also

**Comment by doubotis** [comment]
Maybe a mechanism of "lazy nodes" could be awesome for this specific case.
I explain :

All nodes are hidden by default. When the cursor is near a part of the line, we get the nearest point between the cursor and the line, and display it as a node.
In addition, we display a node for each 3 points before and after (and also the nodes between segments).

This way, the way the editing works is barely different for the client, but it allows the editing of lines with thousand/dozen of thousand points.

**Comment by doubotis** [comment]
Found a solution by only displaying the nodes "near" the cursor. I just subclassed L.Editable classes to handle this way.

**Comment by canadaka** [comment]
@doubotis care to share your solution? I also deal with editing polylines with several thousands of points.

**Comment by doubotis** [comment]
Difficult to give to you my modified version.
I used Draw instead of Editable to do this. I was more comfortable to understand the code in Draw plugin instead of this one. But sure this could be done here.

Basically I commented the init markers creation and add an event listener for mouse move :
```
_handleMouseOver: function(mouseEvent) {
            
            if (this._dragging) return;
            
            // find the point we are the nearest.
            var idx;
            var dist = 20000;
            var latlngs = this._defaultShape();
            for (var i = 1; i < latlngs.length; i++) {
                var ptA = this._map.latLngToLayerPoint(latlngs[i-1]);
                var ptB = this._map.latLngToLayerPoint(latlngs[i]);
                
                var tempDist = L.LineUtil.pointToSegmentDistance(mouseEvent.layerPoint, ptA, ptB);
                //var pt = this._map.latLngToLayerPoint(latlngs[i]);
                //var tempDist = mouseEvent.layerPoint.distanceTo(pt);
                if (tempDist < dist) {
                    idx = i;
                    dist = tempDist;
                }
            }
            var latlng = latlngs[idx];
            
            if (this._nearMarker != null && 
                    this._nearMarker.getLatLng().lat == latlng.lat && 
                    this._nearMarker.getLatLng().lng == latlng.lng) return;     // Do nothing
            
            // Clean the currently displayed elements.
            this._markerGroup.clearLayers();
            this._markers = [];
            
            // Generate main markers.
            for (var i=idx+3; i > idx-3; i--)
            {
                var marker = this._createMarker(latlngs[i], i);
                if (marker != null) {
                    marker.on('click', this._onMarkerClick, this);
                    this._markers.push(marker);
                    
                    if (i == idx)
                        this._nearMarker = marker;
                }
            }
            
            // Loop to create middle markers.
            var markerLeft, markerRight;
            var len = this._markers.length;
            var j;
            for (i = 0, j = len - 1; i < len; j = i++)
            {
                if (i === 0 && !(L.Polygon && (this._poly instanceof L.Polygon))) {
                    continue;
		}
                        
                markerLeft = this._markers[j];
                markerRight = this._markers[i];

                this._createMiddleMarker(markerRight, markerLeft);
                this._updatePrevNext(markerRight, markerLeft);
            }
            
        }
```

You can get my L.Edit.PolyVerticesEdit class. Hope that can helps you.

[L.Edit.PolyVerticesEdit.txt](https://github.com/Leaflet/Leaflet.Editable/files/1068775/L.Edit.PolyVerticesEdit.txt)
