### ISSUE TITLE
L.CircleMarker

### ISSUE THREAD

**Issue by SergeyRyzhkov** [Leaflet/Leaflet.Editable#120]
Hi!
What about L.CircleMarker?

**Comment by prophe05** [comment]
+1

**Comment by cemorris** [comment]
I got L.CircleMaker to work by adding these lines of code to Leaflet.Editable.js
    if (L.CircleMarker) {
        L.CircleMarker.include(EditableMixin);
        L.CircleMarker.include(MarkerMixin);
        L.CircleMarker.addInitHook(keepEditable);
    }

Then set markerClass to L.CircleMarker in your map's editOptions.  i.e.
map = L.map('map', {editable: true, editOptions: {markerClass: L.CircleMarker}});

**Comment by mdj1** [comment]
e cemorris !
Can you be more explicit ?
My goal is to use Leaflet.Editable.js with icons like
in use there:  
http://tkrajina.github.io/leaflet-editable-polyline/example1.html
Can you tell me if you think this possible ?
Thanks.

**Comment by bytesnz** [comment]
@mdj1 to do the same as the example you gave (in terms of the map), you just need to change the styling on the draggable markers. The example  has an editable polyline in it.
