### ISSUE TITLE
Whenever a circle is dragged, L.Editable.CircleEditor attempts to access a non-existent "draggable" property from feature

### ISSUE THREAD

**Issue by axelerate** [Leaflet/Leaflet.Editable#128]
Whenever a circle is dragged, L.Editable.CircleEditor attempts to access a non-existent "draggable" property from feature. Circle does not have such property.

**Comment by yohanboniface** [comment]
I cannot reproduce from http://leaflet.github.io/Leaflet.Editable/example/index.html
