### ISSUE TITLE
.toGeoJSON providing extra points?

### ISSUE THREAD

**Issue by stevelandis** [Leaflet/Leaflet.Editable#132]
I am trying to do something a little bit outside of the box with this library.

I am providing X,Y pixel coordinates to the system.  By clicking Save I would like to output X,Y pixel coordinates.  For some reason it adds 8 points to the polygon when it should only provide 4?

Is there a different way to approach this problem?

From console.log.  
`polygon 0
index.html:157 76,315,245,314,160.5,314.5,281,672,263,493,86,679,183.5,675.5,81,497,
index.html:150 polygon 1
index.html:157 558,292,755,278,656.5,285,739,663,747,470.5,558,663,648.5,663,558,477.5,
index.html:150 polygon 2
index.html:157 160,237,250,227,205,232,248,354,249,290.5,147,361,197.5,357.5,153.5,299,
index.html:150 polygon 3
index.html:157 547,324,712,323,629.5,323.5,712,388,712,355.5,546,396,629,392,546.5,360,`

**Comment by yohanboniface** [comment]
Do you still have this issue? I'm not exactly getting it.
If yes, can you set up a very minimal use case so I can reproduce it?

**Comment by stevelandis** [comment]
I made it work.
