### ISSUE TITLE
Whenever editing a feature, event does not reference control point.

### ISSUE THREAD

**Issue by axelerate** [Leaflet/Leaflet.Editable#133]
If I am dragging a control point marker with the intent of editing a shape, and I am registered to listen for the 'editable:editing' event, the event object that is fired back does not contain references to the dragged control point.

**Comment by yohanboniface** [comment]
`editable:editing` is fired in multiple situations, not only when dragging a vertex.
Listen to a more specific event if you want more specific info: http://leaflet.github.io/Leaflet.Editable/doc/api.html
