### ISSUE TITLE
enableEdit() is not a function

### ISSUE THREAD

**Issue by zindelluib** [Leaflet/Leaflet.Editable#136]
map = new L.Map('mapid', {
          editable: true,
          fullscreenControl: true,
          fullscreenControlOptions: {
            position: 'topleft'
          }
});
That is my configuration for the leaflet map.

I used enableEdit()  so that I can edit the polyline. But it says "enableEdit() is not a function" in the console.

**Comment by yohanboniface** [comment]
Can you be a bit more precise about what the code giving the error?

Just in case, note that `enableEdit` is a method, eg.
```
var marker = L.marker(…);
marker.enableEdit();
```
