### ISSUE TITLE
Edit controls don't show without setView being called

### ISSUE THREAD

**Issue by cryptdemon** [Leaflet/Leaflet.Editable#138]
I've found that none of the demos show their controls without first calling the "setView" method on the map.   

The browser will throw an error like so:  
`Cannot  read property 'startPolyline' of undefined `

`map.editTools` is always undefined when I don't call the setView method first.  Is there a reason for this?

**Comment by yohanboniface** [comment]
Yes, https://github.com/Leaflet/Leaflet.Editable/blob/master/src/Leaflet.Editable.js#L430

The default hooks expect the map to be fully loaded. You can initialize editTools by your self if you want full control.
