### ISSUE TITLE
How to get Latitude and Longitude of marker

### ISSUE THREAD

**Issue by PriyeshT** [Leaflet/Leaflet.Editable#141]
Hello,

Thanks for the amazing plugin.

I am using Leaflet.Editable plugin, to allow users to drop a pin on the map and then drag the marker to new position and display the position.

I enable the edittools.startMarker on click of a button.

I want to get position of the marker when the user drops the pin for the very first time. 
I am able to get the position of the marker after the marker is moved/dragged. But how to get the position of marker when dropped on map?

Thanks,
Priyesh T.
> 
        let marker;	
	$('.marker').on('click', function(e){
		if(marker) {
			map.removeLayer(marker);
		}
		let icon = L.icon({
			iconUrl: '../images/marker-icon.png'
		});
		marker = map.editTools.startMarker(null, {
			icon: icon
		});	
                
		marker.on('moveend', function(e){
			let movedMarker = e.target;
			let newCoord = movedMarker.getLatLng();
		});
		
	});

**Comment by yohanboniface** [comment]
Something like:

```javascript
map.on('editable:drawing:click', function (e) {
    console.log(e.latlng)
}
```
