### ISSUE TITLE
Can't create marker or polyline on Chrome for Android

### ISSUE THREAD

**Issue by opoto** [Leaflet/Leaflet.Editable#146]
I don't know about the root cause, but I noticed Leaflet.Editable does not work properly anymore on Chrome for Android. To reproduce:

- Context: Chrome v60.0.3112.107 on Android 7.0
- open http://leaflet.github.io/Leaflet.Editable/example/index.html
- click on Markers button, then on map: no marker is added
- click on Polyline button, then on map: no polyline is created
...

**Comment by opoto** [comment]
I tried to have a look at the code, but it is beyond my competencies. Does anybody have any hint on what is going wrong? This completely breaks apps using this plugin on Android/Chrome.
Thanks

**Comment by Gjum** [comment]
This is also reproducible using Chrome DevTools, with device emulation enabled (second icon in the top left).

Did you find out between which versions this broke? It's affecting my site as well and I'll have to consider downgrading until this is fixed.

As for what's going wrong, my wild guess is that there are different events (touch?) being emitted on mobile.

**Comment by willemx** [comment]
Can confirm this issue on Chrome for Windows on a Microsoft Surface Pro 4.

**Comment by opoto** [comment]
Actually it doesn't seem to be specific to Leaflet.Editable: I see there is the same issue with [Leaflet.PM](https://leafletpm.now.sh/#/). This is probably an issue in Leaflet itself (or in Chrome, but might be tricky to get it fixed there...).

**Comment by Gjum** [comment]
possibly related to https://github.com/Leaflet/Leaflet/issues/5646?

**Comment by opoto** [comment]
Yes, this looks to be the cause of the issue! Thanks for spotting it.

**Comment by chocho11** [comment]
right, leaflet editable doesnt work on android-chrome : cannot create marker/polyline/polygon !
In Apple (iphone and ipad) does it work ?

**Comment by opoto** [comment]
Yes, works fine on Safari for iOS. As well as on Firefox, Samsung browser, Chrome on Windows... Just failing on Chrome/Android

**Comment by willemx** [comment]
@opoto : Chrome for Windows does not work for me on a Microsoft Surface Pro 4...

**Comment by opoto** [comment]
Following various upgrades (Android, Chrome, Leaflet, Leaflet.Editable...) it works now.
So I'm closing this ticket
