### ISSUE TITLE
Request: Move map when vertex hits border

### ISSUE THREAD

**Issue by kaynz** [Leaflet/Leaflet.Editable#31]
Hey,

first: thanks for the great work.

Could you make the map move when a vertex hits the border of the visible map?

**Comment by yohanboniface** [comment]
> Could you make the map move when a vertex hits the border of the visible map?

Humm, a vertex? Or the drawing mouse? Not sure to understand the scenario if you really mean "a vertex".

**Comment by kaynz** [comment]
the vertex marker, which appear if you poly.enableEdit()

**Comment by yohanboniface** [comment]
But then what to do if two vertices are outside of the visible map, each on one side of the map?

**Comment by kaynz** [comment]
Hm, I think I didn't describe the scenario good enough.

You're dragging ONE marker (You can't drag more than one on the same time). If this marker reaches the map border WHILE dragged, the camera will be moved in the direction of which the marker has been dragged into.

**Comment by kaynz** [comment]
I can create a GIF or a video if its still unclear :)

**Comment by yohanboniface** [comment]
Thanks, it's clear now. Not sure though it should be in Leaflet.Editable core. I'll try to find time to make an example page for such an extension, and see at this point if it makes sense to include it in the core or not.

**Comment by kaynz** [comment]
Any news on this? :)

**Comment by kaynz** [comment]
Just found this: 
https://github.com/Leaflet/Leaflet/pull/3643
