### ISSUE TITLE
Cannot read property 'editTools' of undefined, map var undefined

### ISSUE THREAD

**Issue by rnlke** [Leaflet/Leaflet.Editable#41]
using latest leaflet 1.0, gh-pages Editable, getting error when calling enableEdit(), map var undefined

Leaflet.Editable.js?db208ac5:550 Uncaught TypeError: Cannot read property 'editTools' of undefined

this.tools = this.options.editTools || map.editTools;

**Comment by yohanboniface** [comment]
Can you provide a minimal test case to reproduce the issue http://playground-leaflet.rhcloud.com/ ?

**Comment by yohanboniface** [comment]
Closing here, please reopen with more details if help is still needed.
