### ISSUE TITLE
Ctrl + click is not detected under Chrome and Firefox in OS X

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet.Editable#43]
In this example: http://leaflet.github.io/Leaflet.Editable/example/continue-line.html the meta key detection works, but the control does not (`editable:vertex:ctrlclick`).

Not working: latest Chrome and Firefox
Working: Safari 9.0.1
OS: OS X 10.9.5

I believe it might be something with Ctrl + Click firing a right-click event in OS X. Still, in Safari it's caught and the right click menu is not displayed when clicking on a vertex in that example.

**Comment by yohanboniface** [comment]
Yes, ctrl-click does not work with MacOS©. See https://github.com/Leaflet/Leaflet.Editable/issues/34
