### ISSUE TITLE
UX: startMarker without adding marker in center / under cursor

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet.Editable#45]
Adding a marker provides a very different user experience, compared to adding a polyline or a polygon:
- Polyline and polygon requires the user to click to change the map (like in Photoshop)
- marker puts a marker at the center of the map, and starts moving it as soon as the user moves the cursor

I'm looking for a way to make marker consistent with polyline/polygon, that is not changing the map until the user clicks.

**Comment by yohanboniface** [comment]
@hyperknot work in progress on #45, can you have a try on it by chance?

**Comment by hyperknot** [comment]
@yohanboniface couldn't look at it yet, but the changes look clean and logical, I'll try to use it in the near future.
