### ISSUE TITLE
Hiding/showing editable Layer from Layercontrols making features uneditable

### ISSUE THREAD

**Issue by TimMcCauley** [Leaflet/Leaflet.Editable#47]
First of all: great lib, thanks for your work.

I have added the editable layer to the layer controls:

```layerControls.addOverlay(layerAvoid, 'Avoidable Regions');```

Whenever I toggle this Overlay, meaning remove it and then add it again, I am unable to edit the polygons I drew beforehand. Am I missing anything here or is this actually a bug?

<img width="649" alt="screen shot 2015-12-13 at 11 59 59" src="https://cloud.githubusercontent.com/assets/10322094/11766623/19eb8fd8-a191-11e5-8936-0bde0097bfdd.png">

Cheers and thanks.

**Comment by yohanboniface** [comment]
@TimMcCauley sorry for the lag, I was in a mission in Ethiopia, with close to no Internet and time ;)
Can you have a check with latest trunk (not released yet)?

**Comment by TimMcCauley** [comment]
Thanks.
