### ISSUE TITLE
MultiLineString

### ISSUE THREAD

**Issue by nitrag** [Leaflet/Leaflet.Editable#50]
What would it take to incorporate MultiLineString?

I would like to be able to import GeoJSON, find LineString, create an extension (off-shoot line) from any LineString points, then export back to GeoJSON. 

Alternatively, draw a new line and connect it to another line, therefore merging the two into one MutliLineString.

Is this possible?

**Comment by yohanboniface** [comment]
MultiLineString should aready work. Do you have a usecase where it's not?
