### ISSUE TITLE
Disable interactivity for non-edited layers

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet.Editable#54]
When using Editable, `registerForDrawing` does not disable interactivity with the existing / non-edited layers. This results in:
 - crosshair cursor changing to pointer when hovering over an existing layer
 - events propagating to existing layers, like opening popups, panning, etc. during editing

This is the default behaviour in Leaflet Draw, and would be really nice for usability in Editor.

I only have the following ideas for implementing it:
- `registerForDrawing` should stop events propagating to non-edited layers, and set the icon with `!important`
- loop through all layers and call  `removeInteractiveTarget()` with the appropriate targets on every single layer, and later adding them back individually. This would be probably super expensive when having lots of layers.

**Comment by hyperknot** [comment]
Found out how does Draw do it:
- creates an invisible `leaflet-mouse-marker` divIcon, zIndexes it on top of map
- on each `_onMouseMove`, it moves the mouse marker to be under the cursor
- it registers all clicks, stopping them from even arriving at the other layers

The implementation in Polyline vs Marker is confusing though:
https://github.com/Leaflet/Leaflet.draw/blob/a7aca2553e52943fe671d40f0a1e30dd7a178209/src/draw/handler/Draw.Polyline.js#L66
https://github.com/Leaflet/Leaflet.draw/blob/a7aca2553e52943fe671d40f0a1e30dd7a178209/src/draw/handler/Draw.Marker.js#L26

**Comment by yohanboniface** [comment]
Leaflet.Editable used to have an invisible marker to handle drawing events, but this also has some hard to fix edge cases.

But I agree that this is a very annoying one and must be fixed. Not easy though. I put that on my todolist.

**Comment by hyperknot** [comment]
What were the edge cases? Is it related to the div not moving under the mouse? Something about touch?

I think this might be something where a proper fix would need some features added to Leaflet, wouldn't it? Like a `_disableInteraction` switch on map, featureGroup and layer level possibly?

**Comment by hyperknot** [comment]
@yohanboniface had some time to look at the invisible moving marker case, it's pretty much unusable because the zIndex is continuously changing as the cursor is moving.

I thought a better idea is to make a pane, with zIndex = 1000, width/height: 9999px, and place it inside marker pane.

```
markerPane = document.getElementsByClassName('leaflet-marker-pane')[0];
noClickPane = domUtils.create('div', {
    id: 'no-click-pane'
});

map.editTools.on('editable:drawing:start', function () {
    markerPane.insertBefore(noClickPane, markerPane.children[0]);
});

m.Lmap.editTools.on('editable:drawing:end', function (e) {
        markerPane.removeChild(noClickPane);
});
```

with the following CSS:

```
#no-click-pane {
    //background: blue;
    position: absolute;
    width: 9999px;
    height: 9999px;
    z-index: 1000;
}
```

The only single problem is that middleMarkers' zIndex isn't set in current Editable branch, so I had to modify that. 
https://github.com/hyperknot/Leaflet.Editable/commit/a4f1a8d1475c8197ddf6c22b554711e93e6bd4b1

This seems to working well so far. What do you think?

**Comment by yohanboniface** [comment]
> I thought a better idea is to make a pane, with zIndex = 1000

That's an idea to dig in. I'm currently travelling, so not very focus. I hope to have a bit of time and calm next week-end to go through this important but tricky issue.

**Comment by yohanboniface** [comment]
@hyperknot trying a (hackish) solution, just commit/pushed. This needs a bit more thinking and testing to see it if it can be a proper hook in Leaflet.

**Comment by hyperknot** [comment]
@yohanboniface considering the workaround in Draw or my 9999px noClickPane, this is the elegant solution, definitely not a hack. I'm wondering though, why keeping the targets created during drawing? Isn't the markers supposed to be removed?

**Comment by hyperknot** [comment]
Also, the cursor still changes, even with `!important`. Any ideas for how to fix that?

**Comment by yohanboniface** [comment]
> why keeping the targets created during drawing? Isn't the markers supposed to be removed?

Drawing != editing. After you end drawing you may still edit the layer, dragging the vertices you just created.

> the cursor still changes, even with !important. Any ideas for how to fix that?

I'll have a look.

**Comment by hyperknot** [comment]
I've been looking into this, just some things I noticed:

- `unregisterForDrawing` thus `unblockEvents` is called 2x on stopDrawing(), nothing wrong with that, just wanted to ask you if this is by design?
- I wasn't sure about drawing != editing in the case of continue-line.html example, but it's clear now, it only goes into drawing mode while making a new segment.

**Comment by yohanboniface** [comment]
Let's consider the fix as stable enough and ready for 1.0.

**Comment by ekaitz-zarraga** [comment]
Appeared again in Leaflet 1.2.0.

**Comment by gregallensworth** [comment]
The solution proposed by @hyperknot back in https://github.com/Leaflet/Leaflet.Editable/issues/54#issuecomment-172943690 works well for me.

Leaflet: Leaflet 1.3.4 + Draw 1.0.3

Use case: We have some vector layers with mouse events (tooltips, clicks, the usual) showing on the map. While drawing a `L.Draw.Rectangle` onto the map, we would prefer to suppress those mouse events.

I used the following code. This was adapted for use within a ES2017 class, so your use of `this` and `const` may vary.

```
const markerPane = this.map._container.getElementsByClassName('leaflet-marker-pane')[0];
const clickStopperPane = L.DomUtil.create('div', 'click-stopper-pane');
this.map.on(L.Draw.Event.DRAWSTART, function () {
    markerPane.insertBefore(clickStopperPane, markerPane.children[0]);
}).on(L.Draw.Event.DRAWSTOP, function () {
    markerPane.removeChild(clickStopperPane);
});
```

```
div.leaflet-container {
    .click-stopper-pane {
        position: absolute;
        width: 9999px;
        height: 9999px;
        z-index: 1000;
    }
}
```

Thank you very much for this fix. As far as I can tell, it works perfectly and with no other side effects.
