### ISSUE TITLE
Leaflet.Editable - dragend event doesn't work when ghost vertices are moved

### ISSUE THREAD

**Issue by harishvasireddy** [Leaflet/Leaflet.Editable#59]
Hello,

Here is what I am trying to do: 

I am using leaflet.Editable plugin to draw a editable layer. So, I have a layer and then layer.enableEdit() puts it into edit mode with vertices (some are dark and some are lighter in color). 

Then I am trying to see if the layer is of instance L.Marker and then attaching an event (dragend) to it. So, the next time, I try to move a vertex on the editable layer, i need the dragend to trigger and I am trying to set a flag to use it somewhere else. Issue is it works fine when I drag bright vertices and doesn't work when I try to move a light colored (ghost) vertices. 

Any help is appreciated.

Some code:
if (_Layer instanceof L.Marker) {
                _Layer.on('dragend', (e: any) => {
                    this._isDirty = true;
                });
            }

Thanks!

**Comment by yohanboniface** [comment]
Sorry, missed this, as often with Github notifications mess :(

Why not using Leaflet.Editable events?

```javascript
map.on('editable:drawing:end', function (e) {
    if (e.layer instanceof L.Marker) e.layer.isDirty = true;
});
```

**Comment by yohanboniface** [comment]
Closing as inactive.
