### ISSUE TITLE
Draw polygon programmatically.

### ISSUE THREAD

**Issue by winsento** [Leaflet/Leaflet.Editable#60]
Is possible to draw a new polygon programmatically?

**Comment by yohanboniface** [comment]
If you mean start drawing a polygon:
```
map.editTools.startPolygon()
```

If you mean creating a polygon, just create it with normal Leaflet API, and call `enableEdit()` on it.

If it's something else, please be more specific in your question.

**Comment by winsento** [comment]
@yohanboniface Can I create a polygon fully programmatically (without using the mouse)? 

1. Add vertices knowing lonlat. 
2. Draw several polygons at once.

**Comment by yohanboniface** [comment]
This is just normal Leaflet behaviour, just *create* a Polygon (or edit its latlngs) as you would do without Leaflet.Editable around, and then make them editable calling `polygon.enableEdit()`.
