### ISSUE TITLE
Problems with editTools

### ISSUE THREAD

**Issue by gleysi** [Leaflet/Leaflet.Editable#61]
Hi, i have a problem when i call a function to draw, it shows me the next error:
Cannot read property 'startPolyline' of undefined

What could be the problem if i have the Leaflet.Editable installed.

Thanks :)

**Comment by yohanboniface** [comment]
Hard to say without a bit more context :s

Have you passed `editable: true` as map option?
Are you sure Leaflet.Editable is loaded (404?)?
Can you do `tools = new L.Editable(map)` in your console?

**Comment by gleysi** [comment]
1.- Yes a passed this line 
var map = L.map('map', {editable: true}).setView(startPoint, 16),
      tilelayer = L.tileLayer('http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {maxZoom: 20, attribution: 'Data \u00a9 <a href="http://www.openstreetmap.org/copyright"> OpenStreetMap Contributors </a> Tiles \u00a9 HOT'}).addTo(map);

2.- I´m sure that my Leaflet.Editable is loaded 

3.- When i put tools = new L.Editable(map) in in my console it says this:
Uncaught TypeError: map.addLayer is not a function()              leaflet-src.js

**Comment by yohanboniface** [comment]
Which version of Leaflet are you using and which version of Leaflet.Editable?
Do you have any other error on the console?

**Comment by gleysi** [comment]
Leaflet.Editable:  0.7.0-beta.1
Leaflet:  0.7.7

My errors in my console are just when i want to use a tool like for example when a click in startPolyline
it marks an error that the property is undefined

**Comment by yohanboniface** [comment]
OK, you should use either Leaflet 1.0.0-beta2 or Leaflet.Editable 0.6.2 (should be in the README, if not blame me ;) ).
