### ISSUE TITLE
Wrong vertex connection with closed polyline

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet.Editable#65]
I am using the following code to allow creating a closed polyline (for example a circular hiking track).

```
 map.editTools.on('editable:vertex:mousedown', function (e) {
    var index = e.vertex.getIndex();
    if (index === 0 && map.editTools.drawing() && map.editTools._drawingEditor._drawing === L.Editable.FORWARD && !map.editTools._drawingEditor.CLOSED) {
           map.editTools._drawingEditor.newPointForward(e.latlng);
        map.editTools._drawingEditor.commitDrawing(e);
    }
});
```

The problem is that after disabling and enabling editing on a polyline created like this, when dragging the first point, the line segments are connected to the wrong vertex, see illustration:
![image](https://cloud.githubusercontent.com/assets/494223/13539605/b6707a20-e251-11e5-80de-cc89eade6bb3.png)

Created a playground example here.
https://playground-leaflet.rhcloud.com/cab/1/edit?html,output

Replication: 
1. click 3+ times and finish by clicking on the first vertex
2. click the edit button and drag the first vertex

**Comment by yohanboniface** [comment]
Vertexes are by reference. Try cloning 'e.latlng' before creating new point?

**Comment by hyperknot** [comment]
Thanks a lot, it did it. I didn't think they were attached by reference.
