### ISSUE TITLE
Avoid opening popups after moving markers

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet.Editable#67]
When editing a marker, the popup opens after each movement / dragend.
https://playground-leaflet.rhcloud.com/kan/1/edit?html,output

What would be the best way to disable this? Can we consider this a bug? (I find it goes against the natural editing way of other Editable types, like polyline, polygon, etc. where moving markers does not fire a popup).

The events are fired in the following order: dragend -> preclick -> click -> popupopen

**Comment by yohanboniface** [comment]
Should be fixed by https://github.com/Leaflet/Leaflet.Editable/commit/3cf06c200c5e3cec7cb5f82cb364a8ba886db14a
