### ISSUE TITLE
Initialization bug when map.setView() is not called

### ISSUE THREAD

**Issue by sumothecat** [Leaflet/Leaflet.Editable#68]
When map.setView() is not called and we try to add a control we get:

Uncaught TypeError: Cannot read property 'startPolygon' of undefined

Reproducible easily on the demo page. Thank you for the lib.

**Comment by yohanboniface** [comment]
What you are doing is not very clear to me.
Can you set up a jsfiddle (you can use http://playground-leaflet.rhcloud.com/)?

**Comment by sumothecat** [comment]
Sorry I don't have any time right now.  Easy to reproduce: just remove the call to setView on the demo page and you'll get the error. http://leaflet.github.io/Leaflet.Editable/example/index.html The problem is that you shouldn't need to call map.setView . Thanks

**Comment by yohanboniface** [comment]
Controls are just a demo, they are not part of the lib.

**Comment by chronixlo** [comment]
Came across this bug(?) and it doesn't require controls.

map.editTools is undefined if map center isn't set.

Demo: http://playground-leaflet.rhcloud.com/zama/edit?html,output
