### ISSUE TITLE
Events fired at start

### ISSUE THREAD

**Issue by skol-pro** [Leaflet/Leaflet.Editable#70]
Hi !

I basically just want to call a function when the user has finished drawing a shape (whatever the shape is).

But actually any of the events I tried are just fired at start, never at the end...
```javascript
map.on('editable:drawing:end', function() {
    //...
});
```
I even tried calling `.on()` on **editTools**, same result...
```javascript
map.editTools.on('editable:drawing:end', function() {
    //...
});
```

At first I was expecting **editable:created** to be what I need, same issue.

I really don't think it's a bug, but then, what am I doing wrong ?

**Comment by yohanboniface** [comment]
Which version and which Leaflet version are you using?
Can you reproduce with http://playground-leaflet.rhcloud.com/ ?

**Comment by skol-pro** [comment]
Leaflet @1.0.0-beta.2
Leaflet.Editable from https://github.com/Leaflet/Leaflet.Editable/tree/gh-pages/src

**Comment by skol-pro** [comment]
No one ? Am I using a correct event ? Am I registering the event on the right target ?

**Comment by yohanboniface** [comment]
>  Can you reproduce on http://playground-leaflet.rhcloud.com/ ?

You missed that maybe…


> I found out that the editable:drawing:end works well for polygon, it fires at end. However it fires at start for circle and rectangle.

Ah, interesting, that may be a bug.

**Comment by yohanboniface** [comment]
OK, I see. When drawing Circle or Rectangle, the geometry is created on first click-drag, and then extended. So that's "normal" that the `end` is sent on first click-drag, but I understand that this is not what is expected. I'll have a look.

**Comment by skol-pro** [comment]
Ah sure I see ok.

And so you confirm that there is actually no other event that is fired when a circle or rectangle is created ?

**Comment by skol-pro** [comment]
Hi @yohanboniface  !

Ok so I managed to achieve what I was looking for, using the `editable:editing` event, with a refreshed timeout, whatever, it does the job for any shape :)

Actually, I have two questions for you:
- Is there something embedded regarding shapes dragging ?
- Currently, to "complete" a polygon, I need to double-click, but the double-click also zoom the map, do you have a workaround regarding this (except by disabling the double-click zoom) ?

Thank you !

**Comment by skol-pro** [comment]
Hi again.

Actually I'm facing the event issue again, I'm trying to add tooltip while drawing, but again, only working for lines :-(

**Comment by yohanboniface** [comment]
humm, have you tried using `editable:vertex:dragend`?

**Comment by yohanboniface** [comment]
I'm not sure yet how to fix the `drawing:end` for Circle and Rectangle, given that one is not really *drawing* them when just extending their surface. *drawing* means adding more vertices to a feature.
But I do understand that this behavior is not intuitive in the case of Circle and Rectangle, so I'll to come with something more clever.

**Comment by xoqem** [comment]
I commented in the duplicate I opened, but I have a fix for this, will put up a PR this afternoon or tomorrow.

**Comment by xoqem** [comment]
Here is my potential solution: https://github.com/Leaflet/Leaflet.Editable/pull/91
