### ISSUE TITLE
Publish Rectangle support to npm

### ISSUE THREAD

**Issue by w8r** [Leaflet/Leaflet.Editable#71]
Currently, only the `gh-pages` branch and no npm release have Rectangle editing support. Could you please publish a beta package to npm or let us know what is missing for that to happen, maybe someone can help?

**Comment by yohanboniface** [comment]
I'll do that very soon. I was expecting the release of Leaflet 1.0.0-rc1 to do so.

**Comment by w8r** [comment]
But `leaflet@1.0.0-rc1` is already out, you can also make an RC release. It's just that the product I am currently developing has fallen into the dependency hell because I have to install your component from github, and then it duplicates Leaflet dependency and so on and on.

I am now trying to use your component with two extensions we've came up with, for [dragging](https://github.com/w8r/Leaflet.Editable.Drag) and for [text fields](https://github.com/rumax/Leaflet.Editable.TextBox).

**Comment by yohanboniface** [comment]
> But leaflet@1.0.0-rc1 is already out,

I sort of now that…

> It's just that the product I am currently developing has fallen into the dependency hell because

You can still point to github directly

**Comment by w8r** [comment]
> You can still point to github directly
that's what I'm doing

**Comment by yohanboniface** [comment]
I'm working on this during the week-end.
For now I removed Leaflet from the dependencies, so you don't fall into npm hell.
I need to check some issues and then I'll publish a proper rc release.

**Comment by w8r** [comment]
Thank you so much for doing so and your understanding

**Comment by yohanboniface** [comment]
Pushed 1.0.0-rc.1 on npm.

**Comment by yohanboniface** [comment]
BTW, nice work on Leaflet.Editable.Drag :)
