### ISSUE TITLE
Peer dependency too restrictive in the package.json

### ISSUE THREAD

**Issue by mikeatm** [Leaflet/Leaflet.Editable#72]
Does 1.0-rc need leaflet-rc?  i think it should work with  any  >1.0  leaflet version  right? 
its tripping up my npm installs.

**Comment by yohanboniface** [comment]
I've removed the `peerDependencies`, see Leaflet/Leaflet#4534.

Can you deal with pulling the code from github for now? I'd prefer wait for a Leaflet rc2 before releasing on npm. Because I've the feeling that if rc versions does not match between Leaflet and plugins people will be perturbed. This can be discussed :)

**Comment by mikeatm** [comment]
ok, no problem, it also turns out i did not check my leaflet version properly, so i had an old 0.7x release, which i corrected, so this should not be a priority.

**Comment by theashyster** [comment]
@yohanboniface Thank you for fixing this so fast. And I can for sure deal with pulling it from GitHub for now. :)

**Comment by hyperknot** [comment]
You can also just use this line in package.json, it'll automatically clone and pull from GitHub by magic:

```
"leaflet-editable": "Leaflet/Leaflet.Editable#gh-pages"
```

**Comment by hyperknot** [comment]
OK, I just run into this exact issue and wanted to confirm that the following, minimalistic package.json file cannot `npm install`:

```
{
  "private": true,
  "dependencies": {
    "leaflet": "1.0.0-rc.1",
    "leaflet-editable": "1.0.0-rc.1"
  }
}
```

@yohanboniface can we push an rc1.1 or rc1.2 on the server as now no one can `npm install` Editable and Leaflet in the same project.

**Comment by yohanboniface** [comment]
Strangely, it seems to work for me (but indeed with a warning):
```
leonardo:~/W/p/testnpm npm install
/home/ybon/Work/playground/testnpm
├── UNMET PEER DEPENDENCY leaflet@1.0.0-rc.1
└── leaflet-editable@1.0.0-rc.1 

npm WARN leaflet-editable@1.0.0-rc.1 requires a peer of leaflet@rc but none was installed.
leonardo:~/W/p/testnpm ll node_modules/
total 16K
41944223 4,0K drwxr-xr-x 4 ybon ybon 4,0K  7 mai   10:23 ./
41944219 4,0K drwxr-xr-x 3 ybon ybon 4,0K  7 mai   10:23 ../
41944225 4,0K drwxr-xr-x 7 ybon ybon 4,0K  7 mai   10:23 leaflet/
41944226 4,0K drwxr-xr-x 5 ybon ybon 4,0K  7 mai   10:23 leaflet-editable/
```
May be related to the node/npm version we are using.

Isn't pointing to github an option? I'd prefer not to desync prerelease candidate version numbers between Leaflet and plugins, because I've the filling that we will lose people if one needs to remember that this plugin is rc-1.7 while this other is rc-3, etc. Maybe I'm wrong.

**Comment by theashyster** [comment]
@hyperknot I used the `gh-pages` with `npm` before, but I prefer more version control, though.
I think it could actually be related to the node/npm version in use, yes. I don't know if Leaflet and all its plugins should be in sync with the versioning with Leaflet.

**Comment by hyperknot** [comment]
@yohanboniface maybe aligning plugin versions with exact Leaflet versions it's the best idea, as with semver we could just do 1.0.1 for Editable, while now we'd need to do `1.0.0-rc.1.2` or something silly. The semver thing would be to call this Editable release `1.0.0-rc2` but that'd have a very different meaning.

BTW, here is my npm log (node v0.12.14, npm  v2.15.1):

```
npm WARN peerDependencies The peer dependency leaflet@rc included from leaflet-editable will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.14
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package leaflet@1.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer leaflet-editable@1.0.0-rc.1 wants leaflet@rc

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/nonsync/temp/npm-debug.log
```

**Comment by yohanboniface** [comment]
> node v0.12.14, npm v2.15.1

node v6.1.0, npm 3.8.9… That may explain a lot!

Not sure about your point on versioning here. :s

But let's try to make this clear:

Do anyone **needs** a new npm release to proceed, or going with github link is accepted workaround for this time?

**Comment by hyperknot** [comment]
- I'm happy with the github link
- I recommend releasing Editable as 1.0.0, as Editable can be considered stable even if Leaflet is still changing.

**Comment by theashyster** [comment]
Yes, I have something more similar to @hyperknot versions:
node v0.12.2, npm v2.7.4

That is probably why we experience some issues and @yohanboniface is not experiencing them.

I am fine with the GitHub link, no problem here.
