### ISSUE TITLE
workflow for 0.7 branch

### ISSUE THREAD

**Issue by tomay** [Leaflet/Leaflet.Editable#73]
I have a basic question about workflow, using the 0.7 branch: how to commit edits? 

```javascript
var map = L.map('map',{editable:true});    
var line = map.editTools.startPolyline();    
````

all is well so far; I simply double-click to end the line. Now how do I access it? I need to post this to a database. 

Tried the following, but I get `leaflet.js:6 Uncaught RangeError: Maximum call stack size exceeded`

```javascript
map.on('editable:drawing:end', function(){    
     line.editor.commitDrawing();    
})    
```

thank you

**Comment by yohanboniface** [comment]
Basically something like:
```
map.on('editable:drawing:commit', function (e) {
     doSomethingToSaveInDB(e.layer);
});
```

**Comment by tomay** [comment]
got it, thank you!
