### ISSUE TITLE
Feature Request: Add Rectangle and Circle editing/creation to stable leaflet version.

### ISSUE THREAD

**Issue by ronaldcurtis** [Leaflet/Leaflet.Editable#75]
Would be great if someone could enable the rectangle and circle editing/creation for the stable version of leaflet.

**Comment by yohanboniface** [comment]
Why not upgrading to Leaflet 1.0.0-rc1 instead? that's the (very) near future ;)

**Comment by ronaldcurtis** [comment]
I wish I could! I tried upgrading, but for some reason, click handlers (or any event handlers) on layers created via geojson data are no longer working. I submitted an issue for it. Very weird.

**Comment by yohanboniface** [comment]
> I submitted an issue for it.

Which one?

**Comment by yohanboniface** [comment]
Leaflet 1.0 is very close, so it's unlikely that this will be backported, so closing.
