### ISSUE TITLE
alphanumeric editable

### ISSUE THREAD

**Issue by dejoramo** [Leaflet/Leaflet.Editable#79]
You can change an alphanumeric data of a vector point ?

**Comment by yohanboniface** [comment]
Sorry, I don't get the question. Can you be more explicit/add an example?

**Comment by dejoramo** [comment]
I need a editable date alphanumeric a geojson. It is possible?

**Comment by yohanboniface** [comment]
Seems you want to deal with features properties. Leaflet.Editable only covers editing the geometries, not the attributes, which are not normalized.

I'm closing here because as far as I understand Leaflet.Editable can't help you on this.
