### ISSUE TITLE
"TypeError: layer._pxBounds is undefined" when preferCanvas = true

### ISSUE THREAD

**Issue by osadi** [Leaflet/Leaflet.Editable#80]
Based on the `MultiPolygon` example, with `preferCanvas: true` on the map, trying to add a polygon logs the error `TypeError: layer._pxBounds is undefined`.

Example:
http://playground-leaflet.rhcloud.com/miv/1/edit?html,output

Steps to reproduce on the playground:
1. Doubleclick any shape on the map.
2. Click the button to add a polygon.
3. Click anywhere on the map.

Tested against `gh-master` and leaflet v1.0.0-rc.1

**Comment by yohanboniface** [comment]
Thanks for report!
This bug should be fixed in the master.
Canvas is missing test coverage, so you may issue other bugs :(
I've started a branch to add canvas coverage, but it'll take a bit of time seems (https://github.com/Leaflet/Leaflet.Editable/commit/3f398021bd903d552ffa40df449181bc1db6aec1).
