### ISSUE TITLE
Include is not found

### ISSUE THREAD

**Issue by kaynz** [Leaflet/Leaflet.Editable#83]
Hey,

with latest leaflet-master and latest Leaflet.Editable master:

`Leaflet.Editable.js:1359 Uncaught TypeError: Cannot read property 'include' of undefined(anonymous function) 
@ Leaflet.Editable.js:1359(anonymous function) 
@ Leaflet.Editable.js:17(anonymous function) 
@ Leaflet.Editable.js:20`

1359:

`L.Rectangle.include(EditableMixin);`

**Comment by kaynz** [comment]
Aww, I just noticed that I excluded L.Rectangle in my jake build process. Is there a way to automatically handle this?

**Comment by yohanboniface** [comment]
humm, we can certainly add some checks.
I'll have a look unless you have time yourself.

**Comment by kaynz** [comment]
Hey @yohanboniface,

it would be cool if we could adapt the leaflet build process to remove unused code from leaflet editable. Let's say I've got `jake build[6ienfut,custom]` and I can paste `6ienfut` into the leaflet editable build system and it will automatically drop the unused parts. Is this somehow possible?
