### ISSUE TITLE
Path bounds not updated after dragging

### ISSUE THREAD

**Issue by suurjaak** [Leaflet/Leaflet.Editable#86]
It appears that path boundaries are not updated after dragging. 

Example:
1. Go to demo http://leaflet.github.io/Leaflet.Editable/example/index.html
2. Open the JS console
3. Execute

    map.on("editable:dragend", function(evt) { console.log(evt.layer.getBounds().toBBoxString()); });

Result: dragging a shape on the demo page will always print the same bounds to the console.

**Comment by yohanboniface** [comment]
Fixed by https://github.com/Leaflet/Path.Drag.js/commit/360124d0ca29cd50300adbb87c4962a33f3c720b

Please upgrade leaflet.path.drag to 0.0.3.

**Comment by suurjaak** [comment]
Confirmed, now boundaries get updated after dragging. Thank you. 

One more thing, shouldn't they also update during dragging, for every "editable:drag" event?
