### ISSUE TITLE
I can't pass circleEditorClass option value

### ISSUE THREAD

**Issue by joongtang** [Leaflet/Leaflet.Editable#92]
I can't pass circleEditorClass option value
I wrote code like this. What did I do wrong?
```
map = new L.Map("map", {
  center: new L.LatLng(lat, lng),
  zoom: zoom,
  editable: true,
  editOptions : {
    circleEditorClass: L.Editable.MarkerEditor
  } 
});
```

but this code works well
```
map = new L.Map("map", {
  center: new L.LatLng(lat, lng),
  zoom: zoom,
  editable: true,
  circleEditorClass: L.Editable.MarkerEditor
});
```
Thanks ^^

**Comment by yohanboniface** [comment]
Erf, good catch, the documentation and the code are not in sync!
I'll update the code to make it work in editOptions, but keeping the retrocompat.

**Comment by yohanboniface** [comment]
Fixed, but warning: given that I'm preparing the 1.0 release, and given that a very easy bit to upgrade for users, I've not kept the retrocompat.
