### ISSUE TITLE
Click on polyline marker ineffective after continueForward/continueBackward

### ISSUE THREAD

**Issue by opoto** [Leaflet/Leaflet.Editable#93]
To reproduce:

1. open http://leaflet.github.io/Leaflet.Editable/example/continue-line.html
2. draw a polyline: create a few vertexes
3. click on last vertex to stop polyline extension
4. ctrl-click on last vertex to continue editing
5. click on a existing vertex of this polyline: it should delete it and trigger a "click" event, but it does not. Instead it creates a new vertex at same position.

Note that click event is properly triggered on vertex you create AFTER continueForward/continueBackward

**Comment by yohanboniface** [comment]
Humm, I'm not reproducing on http://leaflet.github.io/Leaflet.Editable/example/continue-line.html
I can continue a line, then click on any vertex to delete it.
Which browser and version are you using?

**Comment by opoto** [comment]
Firefox 48.0 on Win7 64

**Comment by yohanboniface** [comment]
Thanks for the screencast! However I can't read it because I don't have Flash. Any chance you put it somewhere else?

**Comment by opoto** [comment]
Screencast on youtube: https://youtu.be/mAlr2cM0WpE

**Comment by yohanboniface** [comment]
OK, thanks, now I understand the issue.
This is because we totally disable interactivity for the previously added map elements… including vertex markers.
Not easy to fix. I'll think about it.

**Comment by opoto** [comment]
Thanks!
However I wonder why you include this "reset" in vertex.continue(), and not in editor.continueBackward/continueForward ? My application doesn't use a ctrl-click on vertex to continue, but instead it uses an event on the line itself. Hence it doesn't use vertex.continue(), but only line.editor.continueForward(). I thus need to add the reset call also in my app, where I would expect it to be in Leaflet.Editable only.
Thanks anyway

**Comment by yohanboniface** [comment]
Erf, good catch! I'll fix that.

**Comment by yohanboniface** [comment]
Should be good this time, @opoto :)

**Comment by opoto** [comment]
Works fine, thanks!
