### ISSUE TITLE
circle.enableEdit is not a function

### ISSUE THREAD

**Issue by rukayaj** [Leaflet/Leaflet.Editable#94]
Hi, 

I'm encountering the same problem as the one described on this stackoverflow question http://stackoverflow.com/questions/35852284/cant-get-leaflet-editable-working-in-ionic-leaflet-app

I've made a jsfiddle here http://jsfiddle.net/gyompa5b/1/. Am I using the wrong version or something? I tried a few different versions of jquery and leaflet-editable and I can't find the right combination... 

Thanks for your help!

**Comment by yohanboniface** [comment]
Missing links it seems.

**Comment by rukayaj** [comment]
Sorry, I have added them in.

**Comment by yohanboniface** [comment]
Yes, you are using the 0.6.2. Circle edition is only available on the 1.0.0 rc.
