### ISSUE TITLE
Continues drawing

### ISSUE THREAD

**Issue by kuzkok** [Leaflet/Leaflet.Editable#95]
I've try to start new rectangle after one is created, but it's [no work](http://jsbin.com/woyile/2/edit?html,js,output). I do it [with](http://jsbin.com/wilake/7/edit?html,js,output) additional instance of L.Editable, but it looks no so good. Can I do this with default behavior?
Also there are some problems with this if I [disable dragging](http://jsbin.com/wilake/edit?html,js,output)

**Comment by yohanboniface** [comment]
Try with `'editable:drawing:end'` instead of `'editable:drawing:commit'`.

**Comment by kuzkok** [comment]
So simple, thanks.

**Comment by kuzkok** [comment]
There are bug if i only one click on map - plugin draw line from [0,0] to clicked point.

**Comment by kuzkok** [comment]
[here](http://jsbin.com/boxijuc/edit?html,js,output) one more example with some unworking behavior. I want to enable\disable drawing by button. If I only press button for enable startRectangle and then press button for pan - all work as expected. But when I draw something, pressing to pan button not enabling map dragging.

**Comment by yohanboniface** [comment]
>  There are bug if i only one click on map - plugin draw line from [0,0] to clicked point.

Fixed in latest commits.

> here one more example with some unworking behavior

Workarounded. The issue being that by calling `disableEdit` the vertex marker is removed, and thus does not reset it self from drawing. The correct fix may be on Leaflet side. I'll think about this.
