### ISSUE TITLE
Not finish drawing if boundaries outside of the map

### ISSUE THREAD

**Issue by kuzkok** [Leaflet/Leaflet.Editable#96]
In all examples map fills all screen and such beahvior is not seem. 
But if map will be smaller than fullscreen and user drag cursor on drawing outside of map this drawing is not finish.

**Comment by yohanboniface** [comment]
I don't think committing when the user move the mouse out of the map while drawing is a nice thing to do. The user will generally move out the mouse by mistake (if they are *actually* drawing), so it's better to just let them move the mouse in again an continue the drawing.
Plus: should we commit or cancel the drawing? It's not possible to decide.

**Comment by kuzkok** [comment]
May be limit user to drawing only by map div will be better solution
